#!/usr/bin/php
<?

/* Add the commit to the scigit database and update the usable repo. */

require_once '/var/scigit/include/scigit.php';

scigit_db_connect();
$repo_id = intval(exec('git config scigit.repo.id'));
$user_id = intval(substr(getenv('GL_USER'), 1));

$stdin = fopen('php://stdin', 'r');
while ($line = fgets($stdin)) {
	list($old, $new, $ref) = preg_split('/\\s+/', $line);
	$commits = array();
	if (substr_count($old, '0') == strlen($old)) {
		exec("git log --pretty='%H %at %s' $new", $commits);
	} else {
		exec("git log --pretty='%H %at %s' $old..$new", $commits);
	}

	foreach (array_reverse($commits) as $commit) {
		list($hash, $date, $msg) = explode(' ', $commit, 3);
		$msg = addslashes($msg);
		$q = mysql_query('INSERT INTO proj_changes '.
			'(proj_id, user_id, commit_msg, commit_hash, commit_ts) VALUES '.
			"($repo_id, $user_id, '$msg', '$hash', $date)");
		if (!$q) {
			echo "Failed to insert commit into database\n";
			exit(1);
		}
	}
}

chdir(SCIGIT_REPO_DIR);
$repo_name = 'r'.$repo_id;
if (is_dir($repo_name)) {
	chdir($repo_name);
	exec('env -i git pull');
} else {
	exec("env -i git clone git@localhost:$repo_name");
	chdir($repo_name);
	exec('env -i git config core.fileMode false');
}
exec('env -i chmod 755 -R '.SCIGIT_REPO_DIR.'/'.$repo_name);
