#!/bin/sh
# chkconfig: 2345 99 99
# description: Launches SciGit repository manager daemon.

. /lib/lsb/init-functions

NAME=server.py
PIDFILE=/var/run/$NAME.pid
DAEMON=/var/scigit/daemon/$NAME
DAEMON_OPTS="--refresh"

start_scigit() {
    echo "Starting daemon: $NAME"
    start-stop-daemon --start --chuid git --quiet --background --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
    echo "."
}

stop_scigit() {
    echo "Stopping daemon: $NAME"
    killall server.py
    echo "."
}

case "$1" in
    start|"")
      start_scigit
    ;;
    stop)
      stop_scigit
    ;;
    restart|reload|force-reload)
      stop_scigit
      start_scigit
    ;;
    *)
      echo "missing parameter start | stop | restart"
    exit 1
    ;;
esac

exit 0
